# Generated by Django 5.1.5 on 2025-04-02 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inrollment_no', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=64)),
                ('AdharCard', models.BigIntegerField()),
                ('Mobile', models.BigIntegerField()),
                ('Address', models.CharField(max_length=64)),
                ('course', models.CharField(max_length=64)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('Semester', models.IntegerField()),
                ('Fee', models.FloatField()),
            ],
        ),
    ]
