# Generated by Django 5.1.5 on 2025-04-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_studentequery'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpg',
            name='photo',
            field=models.ImageField(default=2, upload_to='student_pics/'),
            preserve_default=False,
        ),
    ]
