# Generated by Django 5.1.5 on 2025-04-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_studentpg_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpg',
            name='Semester',
            field=models.IntegerField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Four')], max_length=1),
        ),
        migrations.AlterField(
            model_name='studentphd',
            name='Semester',
            field=models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Four'), ('5', 'Five'), ('6', 'Six')], max_length=1),
        ),
    ]
