# Generated by Django 5.1.5 on 2025-04-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_alter_studentpg_semester_alter_studentphd_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpg',
            name='course',
            field=models.CharField(choices=[('M.C.A', 'Master of computer Applications'), ('M.Pol.Sc.', 'Master of Political Science'), ('MTS', 'Master of Tribal Studies'), ('M.Soc.', 'Master of Sociology'), ('MSW', 'Master of Social Work'), ('M.P.Ed.', 'Master of Physical Education')], max_length=40),
        ),
        migrations.AlterField(
            model_name='studentphd',
            name='course',
            field=models.CharField(choices=[('PhD-CS', 'Phd computer science'), ('PhD.Pol.Sci.', 'Phd Political Science'), ('PhD-TS', 'Phd Tribal Studies'), ('PhD-SW', 'Phd Social Work'), ('PhD-PE', 'Phd in Physical Education')], max_length=40),
        ),
    ]
