# Generated by Django 5.1.5 on 2025-04-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_alter_studentphd_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentphd',
            name='photo',
            field=models.ImageField(default=2, upload_to='phd_student_pics/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentphd',
            name='Semester',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Four'), (5, 'Five'), (6, 'Six')], max_length=10),
        ),
    ]
