# Generated by Django 5.1.5 on 2025-04-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_studentphd_photo_alter_studentphd_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpg',
            name='signature',
            field=models.ImageField(default=2, upload_to='student_signatures/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentphd',
            name='signature',
            field=models.ImageField(default=2, upload_to='studentphd_signatures/'),
            preserve_default=False,
        ),
    ]
