# Generated by Django 5.1.5 on 2025-04-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_studentpg_signature_studentphd_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inrollment_no', models.IntegerField(null=True, unique=True)),
                ('student_name', models.CharField(max_length=64, null=True)),
                ('Course', models.CharField(choices=[('M.C.A', 'Master of computer Applications'), ('M.Pol.Sc.', 'Master of Political Science'), ('MTS', 'Master of Tribal Studies'), ('M.Soc.', 'Master of Sociology'), ('MSW', 'Master of Social Work'), ('M.P.Ed.', 'Master of Physical Education'), ('PhD-CS', 'Phd computer science'), ('PhD.Pol.Sci.', 'Phd Political Science'), ('PhD-TS', 'Phd Tribal Studies'), ('PhD-SW', 'Phd Social Work'), ('PhD-PE', 'Phd in Physical Education')], max_length=40, null=True)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=10, null=True)),
                ('Semester', models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Four')], max_length=10, null=True)),
                ('Subject_1', models.IntegerField()),
                ('Subject_2', models.IntegerField()),
                ('Subject_3', models.IntegerField()),
                ('Subject_4', models.IntegerField()),
                ('Subject_5', models.IntegerField()),
                ('Total_Obtained', models.IntegerField(default=0, editable=False)),
                ('Total_Marks', models.IntegerField(default=500, editable=False)),
                ('Percentage', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=5)),
                ('status', models.CharField(default='Fail', editable=False, max_length=10)),
            ],
        ),
    ]
