# Generated by Django 5.1.5 on 2025-04-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_marksheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpg',
            name='Semester',
            field=models.CharField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Four')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentphd',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentphd',
            name='Semester',
            field=models.CharField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Four'), (5, 'Five'), (6, 'Six')], max_length=10),
        ),
    ]
