# Generated by Django 5.1.5 on 2025-04-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_alter_studentpg_semester_alter_studentphd_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpg',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=10),
        ),
    ]
