# Generated by Django 5.1.5 on 2025-04-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0014_alter_studentpg_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpg',
            name='Semester',
            field=models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('4', 'Four')], max_length=10),
        ),
    ]
